### ISSUE TITLE
'main' in package.json should point to build/ngProgress.js.

### ISSUE THREAD

**Issue by kentingxu** [VictorBjelkholm/ngProgress#106]
The 'main' file in `package.json` is set to "ngProgess.js". The file doesn't exist in top folder.
`"main": "ngProgress.js",`

It should be changed to "build/ngProgress.js".
`"main": "build/ngProgress.js",`

**Comment by CarlAmbroselli** [comment]
now it references `"main": "build/ngProgress.js"`, but it should reference `"main": "build/ngprogress.js"`.

**Comment by rgroten** [comment]
For consistency, maybe ngprogress.js should be renamed (back to) ngProgress.js.  That's how it's referenced everywhere else.

**Comment by cetra3** [comment]
Resolved by this PR: https://github.com/VictorBjelkholm/ngProgress/pull/77

**Comment by xiphiaz** [comment]
@cetra3 this wasn't resolved in that PR. The `"main"` entry in package.json has been `ngProgress.js` since first commit of `package.json`. See https://github.com/VictorBjelkholm/ngProgress/blame/master/package.json
