### ISSUE TITLE
$http AJAX bind

### ISSUE THREAD

**Issue by zehavibarak** [VictorBjelkholm/ngProgress#107]
Hi,

Can you make it work relatively to the undergoing ajax request?

Thanks

**Comment by cetra3** [comment]
Hi @zehavibarak,

Currently Angular itself is not capable of displaying progress using the `$http` service.  You would need to wait for this PR to land:

https://github.com/angular/angular.js/pull/11547

After that, it would simply be a matter of implementing a callback, updating your ngprogress instance.
