### ISSUE TITLE
Versions missing from npm

### ISSUE THREAD

**Issue by pfgray** [VictorBjelkholm/ngProgress#116]
I'm trying to install this library via npm, and I noticed some versions were missing from the npm repository: https://www.npmjs.com/package/ngprogress

versions in npm: 

```
1.1.1
1.0.6
```

versions in bower:

```
1.1.3
1.1.2
1.1.1
1.1.0
1.0.7
1.0.6
1.0.5
1.0.4
1.0.3
1.0.2
1.0.1
0.0.3
0.0.2
0.0.1
```

I'm mostly interested in the 1.1.2 release, since that includes a fix to the di of `ngProgressFactory`

**Comment by pfgray** [comment]
As a workaround, in order to use the `1.1.2` version, I referenced the release tag on this repository: 
````
npm install VictorBjelkholm/ngProgress#v1.1.2 --save
````
This still isn't preferred, as I'd like to install from npm directly, rather than github.

**Comment by mkalish** [comment]
+1

**Comment by kim222** [comment]
+1

**Comment by cetra3** [comment]
I've looked into this, but don't think I have the appropriate authority to publish this to NPM.  I'll keep investigating.

**Comment by Manningham** [comment]
+1

**Comment by jwanglof** [comment]
+1

**Comment by frame** [comment]
+1

**Comment by kerv2150** [comment]
+1

**Comment by anthw** [comment]
Version 1.1.3 is now released to npm
