### ISSUE TITLE
'main' referenced in package.json doesn't exist.

### ISSUE THREAD

**Issue by pfgray** [VictorBjelkholm/ngProgress#117]
In `package.json`, the "main" file doesn't exist:

````
{
    ...
    "main": "ngProgress.js",
    ...
}
````
It should probably be:

````
{
    ...
    "main": "build/ngprogress.js",
    ...
}
````

This affects how module bundlers, i.e. webpack can parse/bundle this library.
For example, when I import this library, I must fully qualify the path of the file inside this repo:
````
import 'ngprogress/build/ngprogress.js';
````
if the "main" file were correctly referenced, I'd be able to do:
````
import 'ngprogress';
````

**Comment by mkalish** [comment]
+1

**Comment by cetra3** [comment]
Can you open a PR For this?  Thanks

**Comment by Manningham** [comment]
+1

**Comment by cetra3** [comment]
Solved by the PR
