### ISSUE TITLE
setParent() not work

### ISSUE THREAD

**Issue by joaopaulonobrega** [VictorBjelkholm/ngProgress#118]
Hi, first, tks for this  angular plugin.

I 've been testing, everything works perfectly but when I use the function setParent , displays the following error :

**TypeError : this.parent.appendChild is not a function**

follow my code:
   ```
     $scope.progressbar = ngProgressFactory.createInstance();
        
     var element = $scope.progressbar.getDomElement();
     
     $scope.progressbar.setParent(element);
     
     $scope.progressbar.start();
```
to fix the problem I did so :

` $(element).prependTo('body'); ` 

I would like to know where I went wrong , tnks!

**Comment by gngeorgiev** [comment]
My guess is that `element` is not yet added to the DOM.

Also if I recall correctly, this is not a correct usage of the method. You need to pass the `body` here, so that the parent of the progress bar becomes the `body`, not the progress bar itself.

**Comment by cetra3** [comment]
I'm not sure what you're trying to achieve with the sample code, so a bit more of an understanding around this may be better.

You can use setParent on an `element` that doesn't belong to the progressbar itself.  This is really only useful for attaching it to something else rather than the default.

**Comment by gerardorn** [comment]
Ist not working for me either
Code:
HTML
`<div id="container">
      <div id="pbar"></div>
      <div class="main-content container" data-ng-view></div>
    </div>`

JavaScript
`app.controller("MyCtrl", function($scope, ngProgressFactory) {
	$scope.progressbar = ngProgressFactory.createInstance();
	$scope.progressbar.setParent(document.getElementById("pbar"));
	$scope.progressbar.setAbsolute();
        $scope.progressbar.start();
	$scope.progressbar.complete();
});`

Still shows the bar at the top instead of inside the container

**Comment by cetra3** [comment]
You will need to adjust the CSS to adjust the position to be within an element: https://github.com/VictorBjelkholm/ngProgress/blob/master/ngProgress.css
