### ISSUE TITLE
first param in $timeout&progress speed

### ISSUE THREAD

**Issue by pirDOL** [VictorBjelkholm/ngProgress#129]
1 README.md says in Usage

> Use with the API down below
> `$timeout($scope.progressbar.complete(), 1000);`

I'm confused why $timeout is called by
`$timeout($scope.progressbar.complete, 1000);`

2 README,md also says in 'API'

> adds between 0 - 5 percent to loading each 400 milliseconds

Is it possible to support this speed?

thx

**Comment by krysalead** [comment]
Hi,

1 It is an example of how to call the complete function after a 1 second delay.
There is no point of having this code in your code.
2 What do you mean by supporting this speed ? it means that after at minimum of 400*100 milliseconds the progress bar will be complete and at maximum of 400*(100/5) milliseconds

**Comment by anthw** [comment]
Point 1: $timeout is used here as an example to something happening in your own code that takes time. (e.g. an HTTP request).

Point 2: Loading speed is not yet configurable, but there is a PR in at the moment which adds support to modify increments. #60
