### ISSUE TITLE
after deploy code in enviroment - ngprogress version not found

### ISSUE THREAD

**Issue by mrpatel15** [VictorBjelkholm/ngProgress#131]
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9

npm ERR! version not found: ngprogress@1.1.3
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

browse console - Failed to load resource: the server responded with a status of 404 (Not Found)

I tried 1.1.2 and 1.1.3 both , while i deploy code it is coming

**Comment by anthw** [comment]
This is most likely resolved with the recent publish of v1.1.3 to npm. Closing. Please re-open if needed.
