### ISSUE TITLE
NPM Version Request

### ISSUE THREAD

**Issue by teone** [VictorBjelkholm/ngProgress#132]
Hello @VictorBjelkholm, 
thanks for the great module!

there is an issue in using `ngProgress` with a module bundler (webpack/browserify) as the latest `1.1.0-alpha` has the wrong reference in `package.json` as it point to:
```
"main": "ngProgress.js",
```
while it should be:
```
"main": "build/ngProgress.js",
```
and it is correct in `master`.

A temporary workaround for webpack users can be to add an `alias` to your resolve config:
```
resolve: {
    alias: {
      "ngprogress": path.resolve(__dirname, '../node_modules/ngprogress/build/ngProgress.js')
    }
  }
```

**Comment by alihaghighatkhah** [comment]
Because of this issue I have to use your master branch instead of the tag release. Would be great if you have a minor release fixing this issue. Thank you

**Comment by AllenBW** [comment]
@VictorBjelkholm gonna ditto on the above remarks, coulda ya pretty please update npm version, also ❤️ 🌮 💃 🙇‍♀️

**Comment by markalanevans** [comment]
@VictorBjelkholm can you update this to have a release w/ the latest version. No one can use your latest version on npm or yarn.

**Comment by VictorBjelkholm** [comment]
Yeah, npm version 1.1.3 of ngprogress has been released now.
