### ISSUE TITLE
IE not reflecting DOM updates and progress bar is delayed until the page is nearly done loading

### ISSUE THREAD

**Issue by tarekahf** [VictorBjelkholm/ngProgress#134]
I implemented `ngProgress` in my project, and under chrome is works like a charm. However, under IE, the progress bar will show a bit later than it should, in other words, it will appear when the progress starts and completes and when the page is nearly done loading. When the progress bar appears, it will freeze for a short while, then it will complete.  So, not much value here.

How I can force IE to reflect DOM changes immediately?

In my project, I am using directive extensively with `$compile` service, and with lots of bindings.

Appreciate your help.

---
Update: 
I used this approach which helped get better results under IE:

```
app.controller('formMainController', ['$scope', '$timeout', '$interval', 'ngProgressFactory',
                function($scope, $timeout, $interval, $q, ngDialog, ngProgressFactory) {
	$scope.progressbar = ngProgressFactory.createInstance();
	$scope.progressbar.start();
	$scope.stopProgressbar = $interval(function(){
		$scope.progressbar.setParent(document.getElementsByTagName("BODY")[0]);
	},10);
       ...
       ...
       //After getting all data from DB
	$scope.mainPromise.then(function(success) {
		$interval.cancel($scope.stopProgressbar);
		$timeout(function(){
			$scope.progressbar.complete();
		}, 3000);
		return 'main promise done';
	})
}]);
```

With the above, under IE, I can see the progress bar showing much earlier than before, then it will make 2 step progress, then it will freeze for about 2 seconds, then continues normally. When watch the console window, I can see that it will freeze while the other many directives are being executed especially the one that uses `$compile` service with `priority: 100` and `terminal: true,` .

Tarek

**Comment by anthw** [comment]
Glad you found a solution, thanks for sharing. Closing this due to time passed. Please feel free to re-open if needed giving specific IE version for better investigation.
