### ISSUE TITLE
Request for new maintainer

### ISSUE THREAD

**Issue by victorb** [VictorBjelkholm/ngProgress#135]
I currently do not have enough bandwidth to give ngProgress its fair amount of attention so I'm reaching out to y'all to figure out a new maintainer.

The new maintainer would have responsibility over reviewing submitted PRs, triaging issues, improving the code and publishing updates where applicable (bower and npm as of now).

Please leave a comment, send an email to victorbjelkholm@gmail.com or private message on Freenode (victorbjelkholm) if you're interested!

**Comment by anthw** [comment]
I currently work on a project that makes use of this package and I could do with the fixes in 1.3 being published to NPM. I would be happy to do this if you are still looking for a maintainer?

**Comment by VictorBjelkholm** [comment]
@anthw sounds good to me. I've sent you an invite to have write access to this repository. Ping me when I should do a new npm publish. After a version or two, I'd feel comfortable enough to give you access to do the npm publishes yourself.

**Comment by anthw** [comment]
@VictorBjelkholm thanks. Would it be worth pushing the latest version to NPM (1.1.3), as it's only at 1.1.1 at the moment.
