### ISSUE TITLE
Check for conflict with bootstrap navbar because of z-index

### ISSUE THREAD

**Issue by dasois** [VictorBjelkholm/ngProgress#44]
We could maybe have the same problem:
https://github.com/voronianski/ngprogress-lite/pull/18

**Comment by cetra3** [comment]
HI @dasois is this still required?

**Comment by anthw** [comment]
The z-index in ngprogress is already high in the default CSS, so I don't think this would be a problem. Also, users could also override the styling in their own codebase if required.

I will close this issue base on the above. Re-open if you think necessary.
