### ISSUE TITLE
ngProgress.complete() produces "Error: Invalid argument" on IE8

### ISSUE THREAD

**Issue by lukehorvat** [VictorBjelkholm/ngProgress#46]
My test code:

```javascript
.controller("MyCtrl", function($window, $timeout, ngProgress) {
  ngProgress.start();
  $timeout(function() {
    $window.alert("Finished!");
    ngProgress.complete();
  }, 2000);
});
```

Produces the following error in IE8's console:

```
Error: Invalid argument
```

Unfortunately IE doesn't provide a line number or any other info. :(

Commenting out the `ngProgress.complete();` line makes the error go away, so I'm fairly certain the blame lies with that function.

**Comment by cetra3** [comment]
Hi @lukehorvat is this still valid?

**Comment by cetra3** [comment]
Closing this off.  Can reopen if still needed.
