### ISSUE TITLE
the api is not correct

### ISSUE THREAD

**Issue by tommy8694** [VictorBjelkholm/ngProgress#71]
Maybe the provided api is not updated after new version. I used bower install and the version is ngprogress 1.1.1.
read the source code and find that ngProgress.color('#fff') should be : ngProgress.setColor('#fff');
also .setHeight() instead of .height()

**Comment by VictorBjelkholm** [comment]
Hey, the latest version in bower is 1.1.2 according to `bower info ngprogress`. Please try updating the package and let me know if it still is out of sync.
