### ISSUE TITLE
demo not working?

### ISSUE THREAD

**Issue by dciccale** [VictorBjelkholm/ngProgress#72]
http://victorbjelkholm.github.io/ngProgress/

i get a 404 in ngProgress.js

<img width="1177" alt="screen shot 2015-07-30 at 18 41 12" src="https://cloud.githubusercontent.com/assets/539546/8989190/e1ec9e58-36ea-11e5-99ac-70951ffe9606.png">

**Comment by VictorBjelkholm** [comment]
Oh, good catch! Didn't see that.

Should be fixed now, can you try again?

**Comment by dciccale** [comment]
working :+1:

**Comment by VictorBjelkholm** [comment]
Thanks a lot for letting me know! :+1:
