### ISSUE TITLE
Pls Update the API of README.md & website

### ISSUE THREAD

**Issue by paddingme** [VictorBjelkholm/ngProgress#75]
`ngProgress.color();` --> `ngProgress.setColor();`

`ngProgress.height();` --> `ngProgress.setHeight();`

**Comment by paddingme** [comment]
https://github.com/VictorBjelkholm/ngProgress/pull/76

**Comment by VictorBjelkholm** [comment]
Goodie, thanks a lot for this! I've updated the demo in `index.html` also.
