### ISSUE TITLE
Version 1.1.2 uses all-lowercase file naming as opposed to previously used camel-case naming convention

### ISSUE THREAD

**Issue by alex-signature-it** [VictorBjelkholm/ngProgress#78]
Previous versions used to follow camel-case naming convention for the files, e.g. ng**P**rogress/build/ng**P**rogress.js, and now it's 
ng**p**rogress/build/ng**p**rogress.js.

It gets rather confusing/broken if upgraded via bower on a case-sensitive file system, since it'll keep the old camel-case-named files next to new lowercase ones and you might assume you've got a new version while your website will be actually using an old one.

**Comment by VictorBjelkholm** [comment]
Hm, tricky. Npm forced me recently to update my package to only have
lowercase characters in my package name and seems like bower doesn't like
those changes. Not sure I can see a good solution to this. Anyone?

**Comment by alex-signature-it** [comment]
Oh well, if that's intended or forced by the tools change I guess we'll have to live with it.
Thought it was just a typo of sorts.
