### ISSUE TITLE
Backward compatibility of 1.1 with 1.0

### ISSUE THREAD

**Issue by alex-signature-it** [VictorBjelkholm/ngProgress#79]
The changes introduced in 1.1, related to providing a factory ngProgressFactory instead of a service (I presume) ngProgress provided in previous versions are not backward compatible and breaks every single usage of ngProgress.
I understand that this change was necessary in order to be able to provide multiple instances of ngProgress and maybe there were other reasons for it I'm not aware of, but would you consider providing ngProgress service along with ngProgressFactory for backward compatibility?

**Comment by cetra3** [comment]
Hi @alex-signature-it is this still required?

**Comment by alex-signature-it** [comment]
Well, I guess anyone interested in the project have updated their code by now. I know I did.

**Comment by cetra3** [comment]
Ok, I'll close this off.  Thanks!
