### ISSUE TITLE
Blocking fields when progress bar is active

### ISSUE THREAD

**Issue by emirdeliz** [VictorBjelkholm/ngProgress#81]
I have a necessity the blocking fields of form when progress bar is actived. My form contains fields of registers which can not be editable after clicked in button save. 

Any suggestion?

**Comment by cetra3** [comment]
Hi @emirdeliz,

I would say you can manage this with another scope variable that would make the form read only upon submission:

https://docs.angularjs.org/api/ng/directive/ngReadonly
