### ISSUE TITLE
File name capitalisation error

### ISSUE THREAD

**Issue by robwalkerco** [VictorBjelkholm/ngProgress#82]
The css file has a capital P `ngProgress.css`
The js files do not `ngprogress.js`

The bower files build property says that the js file is named `ngProgress.js` which is incorrect.

**Comment by papertrailrob** [comment]
When installing with bower and using grunt wiredep to add bower dependencies into my index.html page, it injects using the wrong name for the js file, which still works fine in my mac Vagrant test environment, but not on the staging server due to stricter capitalisation file name rules.

**Comment by fvezzoso** [comment]
:+1: 

I was about to submit a pull request when I saw that @pauljohncleary already created one here https://github.com/VictorBjelkholm/ngProgress/pull/77

Thanks!

**Comment by cetra3** [comment]
Fixed by https://github.com/VictorBjelkholm/ngProgress/pull/77
