### ISSUE TITLE
API documentation needs update. Bug in readme.md example.

### ISSUE THREAD

**Issue by arlowhite** [VictorBjelkholm/ngProgress#83]
I was using the documentation at:
http://victorbjelkholm.github.io/ngProgress/#installation

These docs need to be updated. It lists height() instead of setHeight() and color() instead of setColor()

Also, readme.md suggests this:

``` javascript
$timeout($scope.progressbar.complete(), 1000);
```

But it should be in a function so it's not called right away:

``` javascript
$timeout(function() {
   $scope.progressbar.complete();
}, 1000);
```

**Comment by cetra3** [comment]
@arlowhite Can you submit a PR for this

**Comment by anthwinter** [comment]
These changes are now in place. Thanks.
