### ISSUE TITLE
Case sensitivity issue

### ISSUE THREAD

**Issue by vijayarulmuthu** [VictorBjelkholm/ngProgress#91]
In the bower.json file, I find the filenames are camel cased, but the actual file (ngprogress.js) is in lowercase. This inconsistency creates a problem on the LINUX environment.  Could you please fix this asap?

  "main": [
    "build/ngProgress.js",
    "ngProgress.css"
  ],

Thanks!

**Comment by schmod** [comment]
Indeed.  This seems to have changed in 1.1.12...

**Comment by Mihail-K** [comment]
We've also run into this issue (and it was very tricky to diagnose).

As a temporary workaround, you can add an override to your bower file,

```json
"overrides": {
  "ngprogress": {
    "main": [
      "build/ngprogress.js",
      "ngProgress.css"
    ]
  }
}
```

Note that you will have to remove it if the issue is resolved in a future version.

**Comment by ttgraham** [comment]
Thank you @Mihail-K for the override. +1 to fixing this, spent my morning tracking down a gulp inconsistency in a new environment.

**Comment by cetra3** [comment]
Fixed by https://github.com/VictorBjelkholm/ngProgress/pull/77
